#!/usr/bin/env python3
"""
Reconcile DugganUSA discovery results into CUE evidence citations.

Reads discovery.json (output of discover.py), cross-references entities
with the current CUE model, and generates a CUE overlay file with
evidence citations for entities that appear in discovered documents.

Usage:
    python3 scripts/reconcile_discovery.py

Input:  discovery.json (in project root)
Output: prints CUE overlay to stdout (redirect to file, review, then merge)
"""

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

# Map of DugganUSA people names → CUE entity IDs
# Add mappings as you discover them
NAME_TO_ID = {
    "Jeffrey Epstein": "epstein",
    "Ghislaine Maxwell": "maxwell",
    "Jean-Luc Brunel": "brunel",
    "Lesley Groff": "lesley_groff",
    "Sarah Kellen": "sarah_kellen",
    "Nadia Marcinkova": "nadia_marcinkova",
    "Leon Black": "leon_black",
    "Les Wexner": "wexner",
    "Steve Cohen": "steve_cohen",
    "Josh Harris": "josh_harris",
    "Peter Thiel": "peter_thiel",
    "Reid Hoffman": "reid_hoffman",
    "Prince Andrew": "prince_andrew",
    "David Copperfield": "david_copperfield",
    "Glenn Dubin": "glenn_dubin",
    "Bill Richardson": "bill_richardson",
    "George Mitchell": "george_mitchell",
    "Joi Ito": "joichi_ito",
    "Joichi Ito": "joichi_ito",
    "Howard Lutnick": "howard_lutnick",
    "Donald Trump": "trump",
    "Jared Kushner": "kushner",
    "Bill Clinton": "bill_clinton",
    "Steve Bannon": "steve_bannon",
    "Alan Dershowitz": "dershowitz",
    "Ken Starr": "ken_starr",
    "Alexander Acosta": "acosta",
    "William Barr": "bill_barr",
    "Geoffrey Berman": "geoffrey_berman",
    "Mark Epstein": "mark_epstein",
    "Bill Gates": "bill_gates",
    "Jes Staley": "jes_staley",
    "Virginia Giuffre": "virginia_giuffre",
    "Virginia Roberts": "virginia_giuffre",
    "Elon Musk": "elon_musk",
    "Jeff Bezos": "jeff_bezos",
    "Harvey Weinstein": "harvey_weinstein",
    "Kevin Spacey": "kevin_spacey",
    "Ehud Barak": "ehud_barak",
    "Woody Allen": "woody_allen",
    "Naomi Campbell": "naomi_campbell",
    "Sergey Brin": "sergey_brin",
    "Larry Summers": "larry_summers",
    "Stephen Hawking": "stephen_hawking",
    "Martin Nowak": "martin_nowak",
    "Lawrence Krauss": "lawrence_krauss",
    "Marvin Minsky": "marvin_minsky",
    "Boris Nikolic": "boris_nikolic",
    "Brad Edwards": "brad_edwards",
    "Sigrid McCawley": "sigrid_mccawley",
    "Philippe Laffont": "philippe_laffont",
    "Adam Back": "adam_back",
    "Brock Pierce": "brock_pierce",
    "Robert Mueller": "robert_mueller",
    "James Comey": "james_comey",
    "Tony Blair": "tony_blair",
    "Peter Mandelson": "peter_mandelson",
}

# Map DugganUSA doc_type → CUE #EvidenceStrength
DOCTYPE_TO_STRENGTH = {
    "efta_release": "documentary",
    "court_filing": "court_filing",
    "financial_record": "financial_record",
    "deposition": "testimonial",
    "fbi_report": "documentary",
    "text_message": "text_message",
    "email": "email",
    "flight_log": "flight_log",
    "photograph": "photograph",
    "investment_record": "financial_record",
}


def main():
    discovery_path = PROJECT_ROOT / "discovery.json"
    if not discovery_path.exists():
        print("ERROR: discovery.json not found.", file=sys.stderr)
        print("Run: python3 scripts/discover.py", file=sys.stderr)
        sys.exit(1)

    with open(discovery_path) as f:
        data = json.load(f)

    docs = data.get("documents_sample", [])
    if not docs:
        print("No documents found in discovery.json", file=sys.stderr)
        sys.exit(1)

    # Build: entity_id → set of (doc_id, strength)
    entity_evidence = {}
    unmatched_people = set()

    for doc in docs:
        doc_id = doc.get("doc_id", "")
        if not doc_id or doc_id == "unknown":
            continue

        doc_type = doc.get("doc_type", "unknown")
        strength = DOCTYPE_TO_STRENGTH.get(doc_type, "documentary")

        for person in doc.get("people", []):
            person = person.strip()
            if not person:
                continue

            entity_id = NAME_TO_ID.get(person)
            if entity_id:
                if entity_id not in entity_evidence:
                    entity_evidence[entity_id] = set()
                entity_evidence[entity_id].add((doc_id, strength))
            else:
                unmatched_people.add(person)

    # Print CUE overlay
    print("// DugganUSA discovery → CUE evidence reconciliation")
    print("// Auto-generated by scripts/reconcile_discovery.py")
    print("// REVIEW BEFORE MERGING — check doc_ids and strength values")
    print("package creeps")
    print()
    print("entities: {")

    for entity_id in sorted(entity_evidence):
        citations = sorted(entity_evidence[entity_id])
        if not citations:
            continue
        # Only output citations we don't already have
        evidence_parts = []
        for doc_id, strength in citations[:5]:  # cap at 5 per entity
            safe_id = doc_id if doc_id.isidentifier() else f'"{doc_id}"'
            evidence_parts.append(f'{safe_id}: "{strength}"')

        joined = ", ".join(evidence_parts)
        print(f"\t{entity_id}: evidence: {{{joined}}}")

    print("}")

    # Report unmatched
    if unmatched_people:
        print(f"\n// {len(unmatched_people)} unmatched people names:", file=sys.stderr)
        for name in sorted(unmatched_people)[:30]:
            print(f"//   {name}", file=sys.stderr)

    print(f"\n// Generated {len(entity_evidence)} entity evidence overlays", file=sys.stderr)
    print(f"// from {len(docs)} discovered documents", file=sys.stderr)


if __name__ == "__main__":
    main()
